// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Cargo
{
    public int CargoId { get; set; }

    public int UserId { get; set; }

    public string Description { get; set; }

    public decimal Weight { get; set; }

    public decimal? Volume { get; set; }

    public string PickupLocation { get; set; }

    public string DropoffLocation { get; set; }

    public string CargoType { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<CargoTrip> CargoTrips { get; set; } = new List<CargoTrip>();

    public virtual User User { get; set; }
}