// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class CargoTrip
{
    public int CargoTripId { get; set; }

    public int CargoId { get; set; }

    public int TripId { get; set; }

    public string Status { get; set; }

    public DateTime? AssignedAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public virtual Cargo Cargo { get; set; }

    public virtual Trip Trip { get; set; }
}