// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Driver
{
    public int DriverId { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string LicenseNumber { get; set; }

    public string LicenseType { get; set; }

    public int? ExperienceYear { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}