// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class OtpToken
{
    public int OtpId { get; set; }

    public int UserId { get; set; }

    public string Email { get; set; }

    public string OtpCodeHash { get; set; }

    public string OtpType { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool? IsUsed { get; set; }

    public int? AttemptCount { get; set; }

    public int? MaxAttempt { get; set; }

    public string IpAddress { get; set; }

    public string UserAgent { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UsedAt { get; set; }

    public virtual User User { get; set; }
}