// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Route
{
    public int RouteId { get; set; }

    public string FromLocation { get; set; }

    public string ToLocation { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();
}