// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Seat
{
    public int SeatId { get; set; }

    public int VehicleId { get; set; }

    public string SeatNumber { get; set; }

    public string SeatType { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();

    public virtual Vehicle Vehicle { get; set; }
}