// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class StaticPage
{
    public int PageId { get; set; }

    public string Title { get; set; }

    public string Slug { get; set; }

    public string Content { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? UpdatedBy { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}