// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Ticket
{
    public int TicketId { get; set; }

    public string TicketCode { get; set; }

    public int BookingId { get; set; }

    public int TripId { get; set; }

    public int SeatId { get; set; }

    public DateTime? IssuedAt { get; set; }

    public DateTime? CheckinAt { get; set; }

    public string Status { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Seat Seat { get; set; }

    public virtual Trip Trip { get; set; }
}