// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Trip
{
    public int TripId { get; set; }

    public int RouteId { get; set; }

    public int VehicleId { get; set; }

    public int? DriverId { get; set; }

    public DateTime DepartureTime { get; set; }

    public DateTime ArrivalTime { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public int? CreatedBy { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<CargoTrip> CargoTrips { get; set; } = new List<CargoTrip>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Route Route { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();

    public virtual Vehicle Vehicle { get; set; }
}